import { OnClickGraphicEffect } from '@/components/client/common/OnClickGraphicEffect'
import { Layout } from '@/components/server/Layout'
import '@/styles/globals.scss'
import type { Metadata } from 'next'
import { Noto_Sans } from 'next/font/google'
import { PropsWithChildren } from 'react'
import { twMerge } from 'tailwind-merge'

const font = Noto_Sans({ subsets: ['latin'], display: 'swap', weight:'400' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  params: {locale}
}: PropsWithChildren<NextAppDirectoryProps>) {
  return (
    <html lang={locale}>
      <body className={twMerge(font.className, "relative")}>
        <Layout>
          {children}
          <OnClickGraphicEffect />
        </Layout>
      </body>
    </html>
  )
}
